nama = "Python"
print(nama[0:3])  # Output: Python
print(nama[3:6])  # Output: PytHon
print(nama[:3])   # Output: Python
print(nama[3:])   # Output: PytHon
print(nama[:])    # Output: Python
print(nama[1:5:2]) # Output: yhn
print(nama[::-1])  # Output: nohtyP
print(nama[5:2:-1]) # Output: noH
print(nama[5:1:-2]) # Output: nhy
print(nama[::2])    # Output: Pto
print(nama[1::2])   # Output: yhn
print(nama[::3])    # Output: Ph
print(nama[1:5:3])  # Output: yh
print(nama[4:1:-1]) # Output: ohy
print(nama[4:1:-2]) # Output: oy
print(nama[3:0:-1]) # Output: Hty
print(nama[3:0:-2]) # Output: Hy
print(nama[2:5:2])  # Output: to
print(nama[2:5:1])  # Output: tho
print(nama[1:4:1])  # Output: yth
print(nama[1:4:2])  # Output: yh
print(nama[0:5:1])  # Output: Python
print(nama[0:5:2])  # Output: Pto
print(nama[0:5:3])  # Output: Ph
print(nama[5:0:-1]) # Output: nohty
print(nama[5:0:-2]) # Output: nht
print(nama[4:0:-1]) # Output: ohyt
print(nama[4:0:-2]) # Output: oyt
print(nama[3:0:-1]) # Output: Hty